/**
 * @generated by `python -m morphe_grammar.artifacts --write`.
 * Source of truth: `py/morphe_grammar/catalog.py`.
 */
import type { CompoundDef } from "./factory.js";

export const PROMOTED_COMPOUNDS = [
	{
		name: "SignalCard",
		version: "1.0.0",
		params: {
			type: "object",
			properties: {
				kicker: {
					type: "node",
					required: true,
					description: "Small register heading for the card.",
				},
				title: {
					type: "node",
					required: true,
					description: "Card title as an authored node.",
				},
				measure: {
					type: "node",
					required: false,
					default: {
						kind: "number",
						value: 0,
						format: "integer",
						intent: "neutral",
					},
					description: "A numeric or textual measure node.",
				},
			},
		},
		template: {
			kind: "frame",
			role: "panel",
			surface: "raised",
			children: [
				{
					kind: "stack",
					role: "panel",
					children: [
						{
							kind: "cluster",
							role: "toolbar",
							justify: "between",
							align: "center",
							children: [
								{
									kind: "param-ref",
									param: "kicker",
								},
								{
									kind: "status",
									tone: "success",
									signal: {
										text: "Ready",
										icon: "check_circle",
									},
								},
							],
						},
						{
							kind: "param-ref",
							param: "title",
						},
						{
							kind: "param-ref",
							param: "measure",
						},
						{
							kind: "slot",
							name: "body",
							fallback: [
								{
									kind: "text",
									value: "No body supplied.",
									as: "caption",
								},
							],
						},
					],
				},
			],
		},
		grammarVersion: "0.2.0",
	},
] as const satisfies readonly CompoundDef[];
