/**
 * @generated by `python -m morphe_grammar.artifacts --write`.
 * Source of truth: `py/morphe_grammar/catalog.py`.
 */
import type { CompoundDef } from "./factory.js";

export const PROMOTED_COMPOUNDS = [
	{
		name: "SignalCard",
		version: "2.0.0",
		params: {
			type: "object",
			properties: {
				kicker: {
					type: "node",
					required: true,
					description: "Small register heading for the card.",
				},
				title: {
					type: "node",
					required: true,
					description: "Card title as an authored node.",
				},
				measure: {
					type: "node",
					required: false,
					description: "A numeric or textual measure node.",
				},
			},
		},
		template: {
			kind: "stack",
			role: "panel",
			children: [
				{
					kind: "cluster",
					role: "toolbar",
					justify: "between",
					align: "center",
					children: [
						{
							kind: "param-ref",
							param: "kicker",
						},
						{
							kind: "slot",
							name: "signal",
							fallback: [],
						},
					],
				},
				{
					kind: "param-ref",
					param: "title",
				},
				{
					kind: "param-ref",
					param: "measure",
				},
				{
					kind: "slot",
					name: "body",
					fallback: [],
				},
			],
		},
		grammarVersion: "0.3.0",
	},
	{
		name: "EntityHeader",
		version: "1.1.0",
		params: {
			type: "object",
			properties: {
				kicker: {
					type: "node",
					required: true,
					description: "Small register line naming the collection this entity is in.",
				},
				title: {
					type: "node",
					required: true,
					description: "The entity's name at display/heading register.",
				},
				keyFigure: {
					type: "node",
					required: false,
					description: "The one number this entity leads with.",
				},
			},
		},
		template: {
			kind: "frame",
			role: "panel",
			surface: "raised",
			children: [
				{
					kind: "stack",
					role: "panel",
					children: [
						{
							kind: "cluster",
							role: "toolbar",
							justify: "between",
							align: "center",
							children: [
								{
									kind: "param-ref",
									param: "kicker",
								},
								{
									kind: "slot",
									name: "signal",
									fallback: [],
								},
							],
						},
						{
							kind: "param-ref",
							param: "title",
						},
						{
							kind: "cluster",
							role: "inline",
							align: "baseline",
							children: [
								{
									kind: "param-ref",
									param: "keyFigure",
								},
								{
									kind: "slot",
									name: "meta",
									fallback: [],
								},
							],
						},
						{
							kind: "slot",
							name: "provenance",
							fallback: [],
						},
					],
				},
			],
		},
		grammarVersion: "0.3.0",
	},
	{
		name: "StatBand",
		version: "1.0.0",
		params: {
			type: "object",
			properties: {},
		},
		template: {
			kind: "grid",
			role: "list",
			minTrack: "narrow",
			children: [
				{
					kind: "slot",
					name: "tiles",
					fallback: [],
				},
			],
		},
		grammarVersion: "0.3.0",
	},
	{
		name: "Breakdown",
		version: "1.0.0",
		params: {
			type: "object",
			properties: {
				title: {
					type: "node",
					required: false,
					default: {
						kind: "text",
						value: "",
						as: "caption",
					},
					description: "Optional heading for the proportion breakdown.",
				},
			},
		},
		template: {
			kind: "stack",
			role: "panel",
			children: [
				{
					kind: "param-ref",
					param: "title",
				},
				{
					kind: "stack",
					role: "list",
					children: [
						{
							kind: "slot",
							name: "rows",
							fallback: [],
						},
					],
				},
			],
		},
		grammarVersion: "0.3.0",
	},
	{
		name: "TrailEntry",
		version: "1.1.0",
		params: {
			type: "object",
			properties: {
				stamp: {
					type: "node",
					required: false,
					default: {
						kind: "text",
						value: "",
						as: "caption",
					},
					description: "Optional temporal stamp for the event.",
				},
				summary: {
					type: "node",
					required: true,
					description: "The event's primary line at body register.",
				},
			},
		},
		template: {
			kind: "stack",
			role: "panel",
			children: [
				{
					kind: "cluster",
					role: "inline",
					align: "baseline",
					children: [
						{
							kind: "param-ref",
							param: "stamp",
						},
						{
							kind: "param-ref",
							param: "summary",
						},
						{
							kind: "slot",
							name: "signals",
							fallback: [],
						},
					],
				},
				{
					kind: "slot",
					name: "detail",
					fallback: [],
				},
				{
					kind: "slot",
					name: "ref",
					fallback: [],
				},
				{
					kind: "slot",
					name: "provenance",
					fallback: [],
				},
			],
		},
		grammarVersion: "0.3.0",
	},
	{
		name: "KeyValuePanel",
		version: "1.0.0",
		params: {
			type: "object",
			properties: {},
		},
		template: {
			kind: "stack",
			role: "panel",
			children: [
				{
					kind: "slot",
					name: "primary",
					fallback: [],
				},
				{
					kind: "slot",
					name: "secondary",
					fallback: [],
				},
				{
					kind: "slot",
					name: "provenance",
					fallback: [],
				},
			],
		},
		grammarVersion: "0.3.0",
	},
] as const satisfies readonly CompoundDef[];
