"""Released grammar fingerprint.

Generated by `python -m morphe_grammar.artifacts --write`. Do not edit.
"""

from __future__ import annotations

from typing import Final

GRAMMAR_FINGERPRINT: Final = (
    "sha256:c0ecb8a72bbb22ed06c5480d7bd0700c28c3ae312a040fd68f8f2ea47f821f1c"
)
