from __future__ import annotations

import json
from typing import Final

# Explicit BMP code-point ranges keep the contract identical in Pydantic's Rust regex,
# JSON Schema's ECMA-262 regex, and the generated TypeScript predicate. Do not replace
# this table with ``\s``/``str.isspace``: those definitions disagree across engines.
INVISIBLE_LABEL_CODE_POINT_RANGES: Final[tuple[tuple[int, int], ...]] = (
    (0x0000, 0x0020),  # C0 controls and ASCII space
    (0x007F, 0x00A0),  # DEL, C1 controls, and no-break space
    (0x00AD, 0x00AD),  # soft hyphen
    (0x034F, 0x034F),  # combining grapheme joiner
    (0x0600, 0x0605),  # Arabic prepended format marks
    (0x061C, 0x061C),  # Arabic letter mark
    (0x06DD, 0x06DD),  # Arabic end-of-ayah format mark
    (0x070F, 0x070F),  # Syriac abbreviation mark
    (0x0890, 0x0891),  # Arabic currency format marks
    (0x08E2, 0x08E2),  # Arabic disputed end-of-ayah format mark
    (0x115F, 0x1160),  # Hangul fillers
    (0x1680, 0x1680),  # ogham space mark
    (0x17B4, 0x17B5),  # Khmer inherent vowels
    (0x180B, 0x180F),  # Mongolian variation/free variation selectors
    (0x2000, 0x200F),  # spaces, zero-width controls, bidi marks
    (0x2028, 0x202F),  # separators, bidi controls, narrow no-break space
    (0x205F, 0x206F),  # mathematical space and invisible/bidi controls
    (0x2800, 0x2800),  # braille pattern blank
    (0x3000, 0x3000),  # ideographic space
    (0x3164, 0x3164),  # Hangul filler
    (0xFE00, 0xFE0F),  # variation selectors
    (0xFEFF, 0xFEFF),  # zero-width no-break space / BOM
    (0xFFA0, 0xFFA0),  # halfwidth Hangul filler
    (0xFFF9, 0xFFFB),  # interlinear annotation controls
)


def _regex_code_point(code_point: int) -> str:
    return f"\\u{code_point:04X}"


def _regex_range(first: int, last: int) -> str:
    start = _regex_code_point(first)
    return start if first == last else f"{start}-{_regex_code_point(last)}"


VISIBLE_LABEL_PATTERN: Final = (
    "[^"
    + "".join(_regex_range(first, last) for first, last in INVISIBLE_LABEL_CODE_POINT_RANGES)
    + "]"
)


def _is_invisible_label_code_point(code_point: int) -> bool:
    return any(first <= code_point <= last for first, last in INVISIBLE_LABEL_CODE_POINT_RANGES)


def has_visible_label_text(value: str) -> bool:
    """Return whether ``value`` contains at least one perceivable label code point."""
    return any(not _is_invisible_label_code_point(ord(character)) for character in value)


def normalize_visible_label_text(value: str, *, fallback: str) -> str:
    """Trim ordinary edge whitespace and replace an invisible-only label."""
    normalized = value.strip()
    if has_visible_label_text(normalized):
        return normalized
    normalized_fallback = fallback.strip()
    if not has_visible_label_text(normalized_fallback):
        msg = "visible-label fallback must contain a perceivable code point"
        raise ValueError(msg)
    return normalized_fallback


def labels_typescript_document() -> str:
    """Render the engine-independent visible-label predicate for TypeScript consumers."""
    ranges = "\n".join(
        f"\t[0x{first:04x}, 0x{last:04x}]," for first, last in INVISIBLE_LABEL_CODE_POINT_RANGES
    )
    return (
        "/**\n"
        " * @generated by `python -m morphe_grammar.artifacts --write`.\n"
        " * Source of truth: `py/morphe_grammar/labels.py`.\n"
        " */\n\n"
        "export const VISIBLE_LABEL_PATTERN =\n"
        f"\t{json.dumps(VISIBLE_LABEL_PATTERN)};\n\n"
        "const INVISIBLE_LABEL_CODE_POINT_RANGES = [\n"
        f"{ranges}\n"
        "] as const;\n\n"
        "function isInvisibleLabelCodePoint(codePoint: number): boolean {\n"
        "\treturn INVISIBLE_LABEL_CODE_POINT_RANGES.some(\n"
        "\t\t([first, last]) => codePoint >= first && codePoint <= last,\n"
        "\t);\n"
        "}\n\n"
        "/** True when a label contains at least one perceivable code point. */\n"
        "export function hasVisibleLabelText(value: string): boolean {\n"
        "\tfor (const character of value) {\n"
        "\t\tconst codePoint = character.codePointAt(0);\n"
        "\t\tif (codePoint !== undefined && !isInvisibleLabelCodePoint(codePoint)) return true;\n"
        "\t}\n"
        "\treturn false;\n"
        "}\n"
    )


__all__ = [
    "INVISIBLE_LABEL_CODE_POINT_RANGES",
    "VISIBLE_LABEL_PATTERN",
    "has_visible_label_text",
    "labels_typescript_document",
    "normalize_visible_label_text",
]
