from __future__ import annotations

from typing import Final

GRAMMAR_VERSION: Final = "0.8.0"


def version_typescript_document() -> str:
    from .fingerprint import compute_grammar_fingerprint  # noqa: PLC0415

    fingerprint = compute_grammar_fingerprint()
    return (
        "/**\n"
        " * @generated by `python -m morphe_grammar.artifacts --write`.\n"
        " * Source of truth: `py/morphe_grammar/version.py` and the generated fingerprint stamp.\n"
        " */\n"
        f'export const GRAMMAR_VERSION = "{GRAMMAR_VERSION}";\n'
        "export const GRAMMAR_FINGERPRINT =\n"
        f'\t"{fingerprint}";\n'
    )


__all__ = ["GRAMMAR_VERSION", "version_typescript_document"]
