from __future__ import annotations

from typing import Final

GRAMMAR_VERSION: Final = "0.4.0"


def version_typescript_document() -> str:
    return (
        "/**\n"
        " * @generated by `python -m morphe_grammar.artifacts --write`.\n"
        " * Source of truth: `py/morphe_grammar/version.py`.\n"
        " */\n"
        f'export const GRAMMAR_VERSION = "{GRAMMAR_VERSION}";\n'
    )


__all__ = ["GRAMMAR_VERSION", "version_typescript_document"]
