from __future__ import annotations

from typing import Final

GRAMMAR_VERSION: Final = "0.8.0"


def version_typescript_document() -> str:
    from .fingerprint import GRAMMAR_FINGERPRINT  # noqa: PLC0415 - avoid version↔fingerprint cycle

    return (
        "/**\n"
        " * @generated by `python -m morphe_grammar.artifacts --write`.\n"
        " * Source of truth: `py/morphe_grammar/version.py`.\n"
        " */\n"
        f'export const GRAMMAR_VERSION = "{GRAMMAR_VERSION}";\n'
        "export const GRAMMAR_FINGERPRINT =\n"
        f'\t"{GRAMMAR_FINGERPRINT}";\n'
    )


__all__ = ["GRAMMAR_VERSION", "version_typescript_document"]
