/**
 * @generated by `python -m morphe_grammar.artifacts --write`.
 * Source of truth: `py/morphe_grammar/labels.py`.
 */

export const VISIBLE_LABEL_PATTERN =
	"[^\\u0000-\\u0020\\u007F-\\u00A0\\u00AD\\u034F\\u0600-\\u0605\\u061C\\u06DD\\u070F\\u0890-\\u0891\\u08E2\\u115F-\\u1160\\u1680\\u17B4-\\u17B5\\u180B-\\u180F\\u2000-\\u200F\\u2028-\\u202F\\u205F-\\u206F\\u2800\\u3000\\u3164\\uFE00-\\uFE0F\\uFEFF\\uFFA0\\uFFF9-\\uFFFB]";

const INVISIBLE_LABEL_CODE_POINT_RANGES = [
	[0x0000, 0x0020],
	[0x007f, 0x00a0],
	[0x00ad, 0x00ad],
	[0x034f, 0x034f],
	[0x0600, 0x0605],
	[0x061c, 0x061c],
	[0x06dd, 0x06dd],
	[0x070f, 0x070f],
	[0x0890, 0x0891],
	[0x08e2, 0x08e2],
	[0x115f, 0x1160],
	[0x1680, 0x1680],
	[0x17b4, 0x17b5],
	[0x180b, 0x180f],
	[0x2000, 0x200f],
	[0x2028, 0x202f],
	[0x205f, 0x206f],
	[0x2800, 0x2800],
	[0x3000, 0x3000],
	[0x3164, 0x3164],
	[0xfe00, 0xfe0f],
	[0xfeff, 0xfeff],
	[0xffa0, 0xffa0],
	[0xfff9, 0xfffb],
] as const;

function isInvisibleLabelCodePoint(codePoint: number): boolean {
	return INVISIBLE_LABEL_CODE_POINT_RANGES.some(
		([first, last]) => codePoint >= first && codePoint <= last,
	);
}

/** True when a label contains at least one perceivable code point. */
export function hasVisibleLabelText(value: string): boolean {
	for (const character of value) {
		const codePoint = character.codePointAt(0);
		if (codePoint !== undefined && !isInvisibleLabelCodePoint(codePoint)) return true;
	}
	return false;
}
