/**
 * @generated by `python -m morphe_grammar.artifacts --write`.
 * Source of truth: `py/morphe_grammar/models.py`.
 */

export type NumberValue = number;

export type JsonValue =
	| null
	| boolean
	| NumberValue
	| string
	| readonly JsonValue[]
	| { readonly [key: string]: JsonValue };

export type ContainerRole =
	| "page"
	| "section"
	| "panel"
	| "toolbar"
	| "list"
	| "form"
	| "field-group"
	| "inline";

export type Density = "compact" | "regular" | "spacious";

export type EmphasisClaim = "muted" | "normal" | "strong" | "critical";

export type GridColumn = "flexible" | "content";

export type CoreIntent =
	| "primary-action"
	| "neutral"
	| "provenance"
	| "evidence"
	| "accession"
	| "caution"
	| "success"
	| "info";

export type IntentRef = CoreIntent | (string & {});

export type VaryId = string & { readonly __morpheVaryId?: never };

export type ParamValue = JsonValue | Node;

export interface VisibleLabelRelation {
	readonly mode: "visible";
	readonly text: string;
}

export interface AriaLabelRelation {
	readonly mode: "aria-label";
	readonly text: string;
}

export interface LabelledByRelation {
	readonly mode: "labelledby";
	readonly id: string;
}

export interface InputA11y {
	readonly id: string;
	readonly label: LabelRelation;
	readonly describedBy?: string;
	readonly required?: boolean;
}

export interface StatusSignal {
	readonly text: string;
	readonly icon?: string;
}

export interface Stack {
	readonly kind: "stack";
	readonly role: ContainerRole;
	readonly direction?: "block" | "inline" | "auto";
	readonly indent?: NumberValue;
	readonly emphasis?: EmphasisClaim;
	readonly children: readonly Node[];
}

export interface Grid {
	readonly kind: "grid";
	readonly role: ContainerRole;
	readonly minTrack?: "narrow" | "regular" | "wide";
	readonly columns?: readonly GridColumn[];
	readonly ruled?: boolean;
	readonly emphasis?: EmphasisClaim;
	readonly children: readonly Node[];
}

export interface Cluster {
	readonly kind: "cluster";
	readonly role: ContainerRole;
	readonly justify?: "start" | "center" | "end" | "between";
	readonly align?: "start" | "center" | "end" | "baseline";
	readonly emphasis?: EmphasisClaim;
	readonly children: readonly Node[];
}

export interface Frame {
	readonly kind: "frame";
	readonly role: ContainerRole;
	readonly surface?: "base" | "raised" | "sunken";
	readonly density?: Density;
	readonly budget?: NumberValue;
	readonly children: readonly Node[];
}

export interface Spacer {
	readonly kind: "spacer";
	readonly size?: "xs" | "sm" | "md" | "lg" | "xl";
}

export interface Text {
	readonly kind: "text";
	readonly value: string;
	readonly as?: "display" | "heading" | "subheading" | "body" | "caption";
	readonly emphasis?: EmphasisClaim;
	readonly intent?: IntentRef;
	readonly clamp?: NumberValue;
	readonly numeric?: boolean;
	readonly polarity?: "positive" | "negative";
}

export interface NumberNode {
	readonly kind: "number";
	readonly value: NumberValue;
	readonly format?: "plain" | "integer" | "currency" | "percent" | "compact";
	readonly currency?: string;
	readonly emphasis?: EmphasisClaim;
	readonly intent?: IntentRef;
}

export interface Badge {
	readonly kind: "badge";
	readonly label: string;
	readonly intent?: IntentRef;
	readonly icon?: string;
}

export interface DecorativeIconA11y {
	readonly role: "decorative";
}

export interface ImageIconA11y {
	readonly role: "img";
	readonly label: string;
}

export interface Icon {
	readonly kind: "icon";
	readonly name: string;
	readonly a11y: IconA11y;
	readonly intent?: IntentRef;
}

export interface MediaSource {
	readonly type: string;
	readonly srcset: string;
}

export interface Media {
	readonly kind: "media";
	readonly src: string;
	readonly alt: string;
	readonly aspect?: "square" | "video" | "portrait" | "auto";
	readonly sources?: readonly MediaSource[];
	readonly sizes?: string;
	readonly width?: NumberValue;
	readonly height?: NumberValue;
	readonly eager?: boolean;
}

export interface Field {
	readonly kind: "field";
	readonly a11y: InputA11y;
	readonly inputType?: "text" | "email" | "password" | "number" | "search" | "tel" | "url";
	readonly placeholder?: string;
	readonly bind?: string;
	readonly hint?: string;
	readonly error?: string;
	readonly multiline?: boolean;
	readonly rows?: NumberValue;
	readonly resizable?: boolean;
}

export interface SelectOption {
	readonly value: string;
	readonly label: string;
	readonly disabled?: boolean;
}

export interface Select {
	readonly kind: "select";
	readonly a11y: InputA11y;
	readonly options: readonly SelectOption[];
	readonly bind?: string;
	readonly hint?: string;
	readonly error?: string;
	readonly variant?: "dropdown" | "radiogroup";
}

export interface Toggle {
	readonly kind: "toggle";
	readonly a11y: InputA11y;
	readonly bind?: string;
	readonly hint?: string;
	readonly variant?: "switch" | "checkbox";
	readonly indeterminate?: boolean;
}

export interface Range {
	readonly kind: "range";
	readonly a11y: InputA11y;
	readonly min: NumberValue;
	readonly max: NumberValue;
	readonly step?: NumberValue;
	readonly bind?: string;
	readonly hint?: string;
}

export interface Progress {
	readonly kind: "progress";
	readonly value?: NumberValue;
	readonly label: string;
	readonly intent?: IntentRef;
}

export interface Status {
	readonly kind: "status";
	readonly tone: "success" | "caution" | "info" | "neutral";
	readonly signal: StatusSignal;
}

export interface InlineAlert {
	readonly kind: "inline-alert";
	readonly tone: "success" | "caution" | "info";
	readonly title: string;
	readonly detail?: string;
	readonly live?: "polite" | "assertive";
}

export interface AriaControlLabel {
	readonly mode: "aria-label";
	readonly text: string;
}

export interface LabelledByControlLabel {
	readonly mode: "labelledby";
	readonly id: string;
}

interface ButtonBase {
	readonly kind: "button";
	readonly variant?: "solid" | "outline" | "ghost";
	readonly intent?: IntentRef;
	readonly type?: "button" | "submit" | "reset";
	readonly disabled?: boolean;
	readonly busy?: boolean;
	readonly action?: string;
	readonly icon?: string;
	readonly id?: string;
}

export type Button =
	| (ButtonBase & { readonly label: string; readonly a11y?: ControlLabel })
	| (ButtonBase & { readonly label?: undefined; readonly a11y: ControlLabel });

export interface Link {
	readonly kind: "link";
	readonly href: string;
	readonly label: string;
	readonly intent?: IntentRef;
	readonly external?: "auto" | "force" | "hide";
}

export interface Dialog {
	readonly kind: "dialog";
	readonly title: string;
	readonly description?: string;
	readonly open?: boolean;
	readonly bind?: string;
	readonly dismissable?: boolean;
	readonly children: readonly Node[];
}

export interface Popover {
	readonly kind: "popover";
	readonly anchor: string;
	readonly id: string;
	readonly placement?: "top" | "bottom" | "start" | "end";
	readonly role?: "tooltip" | "menu" | "listbox";
	readonly open?: boolean;
	readonly bind?: string;
	readonly children: readonly Node[];
}

export interface Disclosure {
	readonly kind: "disclosure";
	readonly summary: string;
	readonly open?: boolean;
	readonly group?: string;
	readonly children: readonly Node[];
}

export interface Slot {
	readonly kind: "slot";
	readonly name: string;
	readonly fallback?: readonly Node[];
}

export interface ParamRef {
	readonly kind: "param-ref";
	readonly param: string;
}

export interface Vary {
	readonly kind: "vary";
	readonly id: string;
	readonly options: readonly Node[];
	readonly default?: NumberValue;
	readonly objective?: "salience" | "density" | "compactness";
}

export interface Within {
	readonly kind: "within";
	readonly id: string;
	readonly dimension: "density" | "emphasis" | "collapse";
	readonly range: readonly [NumberValue, NumberValue];
	readonly default: NumberValue;
}

export interface CompoundRef {
	readonly kind: "compound";
	readonly name: string;
	readonly args: Readonly<Record<string, ParamValue>>;
	readonly emphasis?: EmphasisClaim;
	readonly slots?: Readonly<Record<string, readonly Node[]>>;
}

export type LabelRelation = VisibleLabelRelation | AriaLabelRelation | LabelledByRelation;

export type IconA11y = DecorativeIconA11y | ImageIconA11y;

export type ControlLabel = AriaControlLabel | LabelledByControlLabel;

export type LayoutNode = Stack | Grid | Cluster | Frame | Spacer;

export type ContentNode = Text | NumberNode | Badge | Icon | Media;

export type InputNode = Field | Select | Toggle | Range;

export type FeedbackNode = Progress | Status | InlineAlert;

export type ActionNode = Button | Link;

export type OverlayNode = Dialog | Popover | Disclosure;

export type MetaNode = Slot | ParamRef | Vary | Within;

export type Node =
	| Stack
	| Grid
	| Cluster
	| Frame
	| Spacer
	| Text
	| NumberNode
	| Badge
	| Icon
	| Media
	| Field
	| Select
	| Toggle
	| Range
	| Progress
	| Status
	| InlineAlert
	| Button
	| Link
	| Dialog
	| Popover
	| Disclosure
	| Slot
	| ParamRef
	| Vary
	| Within
	| CompoundRef;

export type NodeKind = Node["kind"];

export function assertNever(value: never): never {
	throw new Error(`Unhandled Node kind: ${JSON.stringify(value)}`);
}
