/**
 * @generated by `python -m morphe_grammar.artifacts --write`.
 * Source of truth: `py/morphe_grammar/dialects.py`.
 */
export const DIALECT_COMPOUND_CONSTRAINTS = {
	"icelandic-archive": {
		mode: "unrestricted",
		compounds: [],
	},
	clinical: {
		mode: "allowlist",
		compounds: ["SignalCard", "EntityHeader", "StatBand"],
	},
	"reykjavik-registry": {
		mode: "unrestricted",
		compounds: [],
	},
	timaeus: {
		mode: "unrestricted",
		compounds: [],
	},
	gallery: {
		mode: "unrestricted",
		compounds: [],
	},
	night: {
		mode: "unrestricted",
		compounds: [],
	},
	ledger: {
		mode: "unrestricted",
		compounds: [],
	},
	estate: {
		mode: "unrestricted",
		compounds: [],
	},
	foundry: {
		mode: "unrestricted",
		compounds: [],
	},
} as const;

export type DialectConstraintId = keyof typeof DIALECT_COMPOUND_CONSTRAINTS;
