/**
 * Generate the immutable identity stamped into edge-compilation receipts.
 *
 * The digest covers the complete synchronous compiler runtime closure plus its
 * package lock. Admission and dialect policy intentionally sit on either side
 * of this identity: the cache key names `(testimony, compiler build)`, while a
 * delivery receipt separately names the selected dialect policy.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");
const outputPath = "src/lib/surface-edge/build-id.generated.ts";
const inputs = [
	"bun.lock",
	"package.json",
	"src/lib/artifacts/source-types.generated.ts",
	"src/lib/artifacts/surface-schema.generated.ts",
	"src/lib/artifacts/surface.ts",
	"src/lib/grammar/labels.ts",
	"src/lib/grammar/types.ts",
	"src/lib/grammar/version.ts",
	"src/lib/surface-edge/build.ts",
	"src/lib/surface-edge/compile.ts",
	"src/lib/surface-edge/emit.ts",
	"src/lib/surface-edge/hints.ts",
	"src/lib/surface-edge/refs.ts",
	"src/lib/surface-edge/resolve.ts",
	"src/lib/surface-edge/spec.ts",
] as const;

function compilerBuildSha256(): string {
	const hash = createHash("sha256");
	hash.update("morphe-compiler-build-v1\0", "utf8");
	for (const relativePath of inputs) {
		hash.update(relativePath, "utf8");
		hash.update("\0", "utf8");
		hash.update(readFileSync(resolve(repoRoot, relativePath)));
		hash.update("\0", "utf8");
	}
	return `sha256:${hash.digest("hex")}`;
}

function generatedModule(): string {
	const inputLines = inputs.map((path) => ` * - ${path}`).join("\n");
	return `/**
 * Generated by scripts/compiler-build-id.ts. Do not edit by hand.
 *
 * Runtime inputs:
${inputLines}
 */
export const COMPILER_BUILD_SHA256 =
\t"${compilerBuildSha256()}" as const;
`;
}

const mode = process.argv[2];
const expected = generatedModule();
const absoluteOutput = resolve(repoRoot, outputPath);

if (mode === "--write") {
	writeFileSync(absoluteOutput, expected, "utf8");
	process.stdout.write(`wrote ${outputPath}\n`);
} else if (mode === "--check") {
	let actual = "";
	try {
		actual = readFileSync(absoluteOutput, "utf8");
	} catch {
		// The mismatch below gives one stable repair command for absent and stale output.
	}
	if (actual !== expected) {
		throw new Error(`${outputPath} is stale; run bun scripts/compiler-build-id.ts --write`);
	}
	process.stdout.write(`compiler build identity is current: ${compilerBuildSha256()}\n`);
} else {
	throw new Error("usage: bun scripts/compiler-build-id.ts --check|--write");
}
