/**
 * embed-corpus.ts — precompute the capability RETRIEVAL embeddings (ADR-0002, WS9).
 *
 * Stage 1 of the composer's two-stage ranking pipeline is an in-memory cosine
 * retriever; it needs one vector per capability. We embed each capability's
 * `documentText(cap)` with Voyage `voyage-4-large` (input_type "document", 1024
 * dims) ONCE, at build time, and COMMIT the result — so deploys are deterministic
 * and the runtime never re-embeds documents (only the visitor's query, per request).
 *
 * Run:  bun scripts/embed-corpus.ts        (reads VOYAGE_API_KEY from .env)
 * Emits (committed): src/lib/compose/embeddings.ts (NB: NOT under generated/, which is
 * gitignored — these embeddings are deliberately committed, per ADR-0002).
 *
 * Regenerate whenever the corpus TEXT changes; `embeddings.test.ts` enforces the
 * invariant that every capability id has a vector of the right dimension (the
 * retrieval analogue of the dialect keyset fixed point).
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { CAPABILITIES } from "../src/lib/compose/corpus.js";
import { documentText } from "../src/lib/compose/document.js";

const VOYAGE_EMBED_URL = "https://api.voyageai.com/v1/embeddings";
const MODEL = "voyage-4-large";
const DIMENSION = 1024;
const INPUT_TYPE = "document";
/** Conservative per-request batch — well under voyage-4-large's 1000-text / 120K-token caps even at ~1000 capabilities. */
const BATCH = 128;
/** 6 decimals: negligible cosine error, roughly halves the committed file size vs full float repr. */
const PRECISION = 1e6;

const OUT = resolve(import.meta.dirname, "..", "src", "lib", "compose", "embeddings.ts");

interface EmbedResponse {
	data?: { index: number; embedding: number[] }[];
}

async function embedBatch(texts: string[], key: string): Promise<number[][]> {
	const res = await fetch(VOYAGE_EMBED_URL, {
		method: "POST",
		headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
		body: JSON.stringify({
			input: texts,
			model: MODEL,
			input_type: INPUT_TYPE,
			output_dimension: DIMENSION,
		}),
	});
	if (!res.ok) {
		throw new Error(`Voyage ${res.status}: ${await res.text()}`);
	}
	const payload = (await res.json()) as EmbedResponse;
	const data = payload.data ?? [];
	if (data.length !== texts.length) {
		throw new Error(`Voyage returned ${data.length} embeddings for ${texts.length} inputs`);
	}
	// Order by the returned index defensively, then take the raw vectors.
	return [...data].sort((a, b) => a.index - b.index).map((d) => d.embedding);
}

function round(v: number): number {
	return Math.round(v * PRECISION) / PRECISION;
}

async function main(): Promise<void> {
	const key = process.env.VOYAGE_API_KEY;
	if (!key) {
		throw new Error("VOYAGE_API_KEY is not set (expected in .env).");
	}

	// Stable id order so the committed file diffs cleanly across regenerations.
	const caps = [...CAPABILITIES].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
	const byId: Record<string, number[]> = {};

	for (let i = 0; i < caps.length; i += BATCH) {
		const slice = caps.slice(i, i + BATCH);
		const vectors = await embedBatch(slice.map(documentText), key);
		slice.forEach((cap, j) => {
			const vec = vectors[j];
			if (!vec || vec.length !== DIMENSION) {
				throw new Error(`bad embedding for ${cap.id}: length ${vec?.length ?? "none"}`);
			}
			byId[cap.id] = vec.map(round);
		});
		// biome-ignore lint/suspicious/noConsole: build script progress output.
		console.log(`embedded ${Math.min(i + BATCH, caps.length)}/${caps.length}`);
	}

	// A 100K-number array literal makes tsc/svelte-check crawl; a single JSON string
	// literal type-checks in O(1) and parses once at server module-load.
	const raw = JSON.stringify(JSON.stringify(byId));
	const file = [
		"// GENERATED by scripts/embed-corpus.ts — do not edit by hand.",
		`// Model ${MODEL} · ${DIMENSION} dims · input_type ${INPUT_TYPE} · ${caps.length} capabilities.`,
		"// Regenerate when the corpus text changes: bun scripts/embed-corpus.ts",
		"",
		`export const EMBEDDINGS_META = { model: ${JSON.stringify(MODEL)}, dimension: ${DIMENSION}, count: ${caps.length} } as const;`,
		"",
		"/** Capability id -> retrieval embedding (voyage-4-large, document space). Parsed once at load. */",
		`export const CAPABILITY_EMBEDDINGS = JSON.parse(${raw}) as Record<string, readonly number[]>;`,
		"",
	].join("\n");

	writeFileSync(OUT, file, "utf8");
	// biome-ignore lint/suspicious/noConsole: build script progress output.
	console.log(`wrote ${OUT} (${caps.length} vectors, ${MODEL}/${DIMENSION})`);
}

main().catch((err: unknown) => {
	console.error(err);
	process.exit(1);
});
