from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from .schema import surface_artifact_schema_document

if TYPE_CHECKING:
    from morphe_grammar.schema import JsonSchema

ARTIFACT_PATHS: tuple[str, ...] = (
    "schema/morphe-surface-artifact.schema.json",
    "src/lib/artifacts/surface-schema.generated.ts",
)


def _json_document(document: JsonSchema) -> str:
    return json.dumps(document, ensure_ascii=True, indent=2, sort_keys=True) + "\n"


def _typescript_document(document: JsonSchema) -> str:
    encoded = json.dumps(document, ensure_ascii=True, indent=2, sort_keys=True)
    template_safe = encoded.replace("`", "\\u0060").replace("${", "\\u0024{")
    return (
        "/**\n"
        " * @generated by `python -m morphe_surface.artifacts --write`.\n"
        " * Source of truth: `py/morphe_surface/artifact.py` and the Pydantic Node grammar.\n"
        " */\n"
        "export const SURFACE_ARTIFACT_JSON_SCHEMA = JSON.parse(\n"
        f"\tString.raw`{template_safe}`,\n"
        ") as unknown as Record<string, unknown>;\n"
    )


def artifact_documents() -> dict[str, str]:
    schema = surface_artifact_schema_document()
    return {
        ARTIFACT_PATHS[0]: _json_document(schema),
        ARTIFACT_PATHS[1]: _typescript_document(schema),
    }


def write_artifacts(root: Path = Path()) -> None:
    for relative_path, contents in artifact_documents().items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")


def changed_artifacts(root: Path = Path()) -> tuple[str, ...]:
    return tuple(
        relative_path
        for relative_path, contents in artifact_documents().items()
        if not (root / relative_path).exists()
        or (root / relative_path).read_text(encoding="utf-8") != contents
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Generate/check surface artifact contracts.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated artifacts")
    mode.add_argument("--check", action="store_true", help="verify committed artifacts")
    args = parser.parse_args(argv)

    if args.write:
        write_artifacts()
        return

    changed = changed_artifacts()
    if changed:
        for relative_path in changed:
            sys.stderr.write(f"stale generated artifact: {relative_path}\n")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
