from __future__ import annotations

import json
import types
from datetime import datetime
from typing import Annotated, Literal, Union, get_args, get_origin

from pydantic import BaseModel

from morphe_contracts import Diagnostic

from .source import (
    Ed25519Attestation,
    SourceSeals,
    SourceSurfaceArtifactV1,
    ViewModelContract,
)

_NONE_TYPE = type(None)
_TYPE_ALIAS_NAMES = {"JsonObject", "JsonValue", "Sha256"}
_MODEL_TYPES = (
    Diagnostic,
    ViewModelContract,
    SourceSeals,
    Ed25519Attestation,
    SourceSurfaceArtifactV1,
)
_LINE_WIDTH = 100
_VARIADIC_TUPLE_ARITY = 2


def _unwrap_annotated(annotation: object) -> object:
    if get_origin(annotation) is Annotated:
        return get_args(annotation)[0]
    return annotation


def _alias_name(annotation: object) -> str | None:
    name = getattr(annotation, "__name__", None)
    return name if isinstance(name, str) and name in _TYPE_ALIAS_NAMES else None


def _typescript_type(annotation: object) -> str:  # noqa: C901, PLR0911
    annotation = _unwrap_annotated(annotation)
    alias = _alias_name(annotation)
    if alias is not None:
        return alias
    if annotation is _NONE_TYPE:
        return "null"
    if annotation is str or annotation is datetime:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"

    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Literal:
        return " | ".join(json.dumps(value, ensure_ascii=True) for value in args)
    if origin in {Union, types.UnionType}:
        return " | ".join(_typescript_type(arg) for arg in args)
    if origin is tuple:
        if len(args) == _VARIADIC_TUPLE_ARITY and args[1] is Ellipsis:
            return f"readonly {_typescript_type(args[0])}[]"
        return f"readonly [{', '.join(_typescript_type(arg) for arg in args)}]"
    if origin is list:
        return f"readonly {_typescript_type(args[0])}[]"
    if origin is dict:
        return f"Readonly<Record<string, {_typescript_type(args[1])}>>"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    msg = f"unsupported source-artifact annotation: {annotation!r}"
    raise TypeError(msg)


def _interface_field(name: str, annotation: object, *, required: bool) -> str:
    optional = "" if required else "?"
    rendered = _typescript_type(annotation)
    inline = f"\treadonly {name}{optional}: {rendered};"
    if len(inline) <= _LINE_WIDTH:
        return inline
    return f"\treadonly {name}{optional}:\n\t\t{rendered};"


def _interface(model_type: type[BaseModel]) -> str:
    lines = [f"export interface {model_type.__name__} {{"]
    for field_name, field in model_type.model_fields.items():
        lines.append(
            _interface_field(
                field.alias or field_name,
                field.annotation,
                required=field.is_required(),
            )
        )
    lines.append("}")
    return "\n".join(lines)


def source_typescript_document() -> str:
    """Generate readonly TypeScript ingress types from the Pydantic wire models."""
    blocks = [
        (
            "/**\n"
            " * @generated by `python -m morphe_surface.artifacts --write`.\n"
            " * Source of truth: `py/morphe_surface/source.py` and "
            "`py/morphe_contracts/__init__.py`.\n"
            " */"
        ),
        "export type Sha256 = `sha256:${string}`;",
        (
            "export type JsonValue =\n"
            "\t| null\n"
            "\t| boolean\n"
            "\t| number\n"
            "\t| string\n"
            "\t| readonly JsonValue[]\n"
            "\t| { readonly [key: string]: JsonValue };"
        ),
        "export type JsonObject = { readonly [key: string]: JsonValue };",
        *(_interface(model_type) for model_type in _MODEL_TYPES),
    ]
    return "\n\n".join(blocks) + "\n"


__all__ = ["source_typescript_document"]
