/**
 * @generated by `python -m morphe_surface.artifacts --write`.
 * Source of truth: `py/morphe_surface/source.py`.
 */
export const SOURCE_SURFACE_ARTIFACT_JSON_SCHEMA = JSON.parse(
	String.raw`{
  "$defs": {
    "Diagnostic": {
      "additionalProperties": false,
      "properties": {
        "code": {
          "title": "Code",
          "type": "string"
        },
        "message": {
          "title": "Message",
          "type": "string"
        },
        "path": {
          "title": "Path",
          "type": "string"
        },
        "repair_hint": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Repair Hint"
        },
        "severity": {
          "enum": [
            "error",
            "warning",
            "info"
          ],
          "title": "Severity",
          "type": "string"
        }
      },
      "required": [
        "code",
        "severity",
        "path",
        "message"
      ],
      "title": "Diagnostic",
      "type": "object"
    },
    "Ed25519Attestation": {
      "additionalProperties": false,
      "properties": {
        "algorithm": {
          "const": "Ed25519",
          "title": "Algorithm",
          "type": "string"
        },
        "key_id": {
          "title": "Key Id",
          "type": "string"
        },
        "signature": {
          "pattern": "^[A-Za-z0-9_-]{85}[AQgw]$",
          "title": "Signature",
          "type": "string"
        }
      },
      "required": [
        "algorithm",
        "key_id",
        "signature"
      ],
      "title": "Ed25519Attestation",
      "type": "object"
    },
    "JsonObject": {
      "additionalProperties": {
        "$ref": "#/$defs/JsonValue"
      },
      "type": "object"
    },
    "JsonValue": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "integer"
        },
        {
          "type": "number"
        },
        {
          "type": "string"
        },
        {
          "items": {
            "$ref": "#/$defs/JsonValue"
          },
          "type": "array"
        },
        {
          "additionalProperties": {
            "$ref": "#/$defs/JsonValue"
          },
          "type": "object"
        },
        {
          "type": "null"
        }
      ]
    },
    "Sha256": {
      "pattern": "^sha256:[0-9a-f]{64}$",
      "type": "string"
    },
    "SourceSeals": {
      "additionalProperties": false,
      "properties": {
        "content_sha256": {
          "$ref": "#/$defs/Sha256"
        },
        "schema_sha256": {
          "$ref": "#/$defs/Sha256"
        },
        "testimony_sha256": {
          "$ref": "#/$defs/Sha256"
        }
      },
      "required": [
        "schema_sha256",
        "content_sha256",
        "testimony_sha256"
      ],
      "title": "SourceSeals",
      "type": "object"
    },
    "ViewModelContract": {
      "additionalProperties": false,
      "properties": {
        "hint_vocabulary": {
          "title": "Hint Vocabulary",
          "type": "string"
        },
        "id": {
          "title": "Id",
          "type": "string"
        },
        "revision": {
          "minimum": 1,
          "title": "Revision",
          "type": "integer"
        },
        "schema_dialect": {
          "const": "https://json-schema.org/draft/2020-12/schema",
          "title": "Schema Dialect",
          "type": "string"
        }
      },
      "required": [
        "id",
        "revision",
        "schema_dialect",
        "hint_vocabulary"
      ],
      "title": "ViewModelContract",
      "type": "object"
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "attestation": {
      "$ref": "#/$defs/Ed25519Attestation"
    },
    "data": {
      "$ref": "#/$defs/JsonValue"
    },
    "diagnostics": {
      "default": [],
      "items": {
        "$ref": "#/$defs/Diagnostic"
      },
      "title": "Diagnostics",
      "type": "array"
    },
    "issuer": {
      "title": "Issuer",
      "type": "string"
    },
    "kind": {
      "const": "morphe.source-surface",
      "title": "Kind",
      "type": "string"
    },
    "produced_at": {
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "title": "Produced At",
      "type": "string"
    },
    "required_capabilities": {
      "default": [],
      "items": {
        "type": "string"
      },
      "title": "Required Capabilities",
      "type": "array"
    },
    "schema": {
      "$ref": "#/$defs/JsonObject"
    },
    "seals": {
      "$ref": "#/$defs/SourceSeals"
    },
    "source_revision": {
      "title": "Source Revision",
      "type": "string"
    },
    "surface_id": {
      "pattern": "^[a-z0-9_-]+\\.[a-z0-9_-]+(?::[A-Za-z0-9_-]+)+$",
      "title": "Surface Id",
      "type": "string"
    },
    "valid_until": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "title": "Valid Until"
    },
    "view_model": {
      "$ref": "#/$defs/ViewModelContract"
    },
    "wire_version": {
      "const": "1.0",
      "title": "Wire Version",
      "type": "string"
    }
  },
  "required": [
    "kind",
    "wire_version",
    "issuer",
    "surface_id",
    "source_revision",
    "produced_at",
    "view_model",
    "schema",
    "data",
    "seals",
    "attestation"
  ],
  "title": "Morphe Source Surface Artifact V1",
  "type": "object"
}`,
) as unknown as Record<string, unknown>;
