/**
 * @generated by `python -m morphe_surface.artifacts --write`.
 * Source of truth: `py/morphe_surface/source.py` and `py/morphe_contracts/__init__.py`.
 */

export type Sha256 = `sha256:${string}`;

export type JsonValue =
	| null
	| boolean
	| number
	| string
	| readonly JsonValue[]
	| { readonly [key: string]: JsonValue };

export type JsonObject = { readonly [key: string]: JsonValue };

export interface Diagnostic {
	readonly code: string;
	readonly severity: "error" | "warning" | "info";
	readonly path: string;
	readonly message: string;
	readonly repair_hint?: string | null;
	readonly href?: string | null;
}

export interface ViewModelContract {
	readonly id: string;
	readonly revision: number;
	readonly schema_dialect: "https://json-schema.org/draft/2020-12/schema";
	readonly hint_vocabulary: string;
}

export interface SourceSeals {
	readonly schema_sha256: Sha256;
	readonly content_sha256: Sha256;
	readonly testimony_sha256: Sha256;
}

export interface Ed25519Attestation {
	readonly algorithm: "Ed25519";
	readonly key_id: string;
	readonly signature: string;
}

export interface SourceSurfaceArtifactV1 {
	readonly kind: "morphe.source-surface";
	readonly wire_version: "1.0";
	readonly issuer: string;
	readonly surface_id: string;
	readonly source_revision: string;
	readonly produced_at: string;
	readonly valid_until?: string | null;
	readonly view_model: ViewModelContract;
	readonly schema: JsonObject;
	readonly data: JsonValue;
	readonly diagnostics?: readonly Diagnostic[];
	readonly required_capabilities?: readonly string[];
	readonly seals: SourceSeals;
	readonly attestation: Ed25519Attestation;
}
