/**
 * Generated by scripts/compiler-build-id.ts. Do not edit by hand.
 *
 * Runtime inputs:
 * - bun.lock
 * - package.json
 * - src/lib/artifacts/source-types.generated.ts
 * - src/lib/artifacts/surface-schema.generated.ts
 * - src/lib/artifacts/surface.ts
 * - src/lib/grammar/labels.ts
 * - src/lib/grammar/types.ts
 * - src/lib/grammar/version.ts
 * - src/lib/surface-edge/build.ts
 * - src/lib/surface-edge/compile.ts
 * - src/lib/surface-edge/emit.ts
 * - src/lib/surface-edge/hints.ts
 * - src/lib/surface-edge/refs.ts
 * - src/lib/surface-edge/resolve.ts
 * - src/lib/surface-edge/spec.ts
 */
export const COMPILER_BUILD_SHA256 =
	"sha256:fd11528dda3d67a5bd4865275faaa636891d3ec741f3ae8ccd86b28e3e2d30fe" as const;
