/**
 * Generated by scripts/compiler-build-id.ts. Do not edit by hand.
 *
 * Runtime inputs:
 * - bun.lock
 * - package.json
 * - src/lib/artifacts/source-types.generated.ts
 * - src/lib/artifacts/surface-schema.generated.ts
 * - src/lib/artifacts/surface.ts
 * - src/lib/grammar/labels.ts
 * - src/lib/grammar/types.ts
 * - src/lib/grammar/version.ts
 * - src/lib/surface-edge/build.ts
 * - src/lib/surface-edge/compile.ts
 * - src/lib/surface-edge/emit.ts
 * - src/lib/surface-edge/hints.ts
 * - src/lib/surface-edge/refs.ts
 * - src/lib/surface-edge/resolve.ts
 * - src/lib/surface-edge/spec.ts
 */
export const COMPILER_BUILD_SHA256 =
	"sha256:a52b0f31e7cc07ae0a27025c0734fbc2fcf3d1dc99c589109df1ccc57841d067" as const;
