/**
 * Generated by scripts/compiler-build-id.ts. Do not edit by hand.
 *
 * Runtime inputs:
 * - bun.lock
 * - package.json
 * - src/lib/artifacts/source-types.generated.ts
 * - src/lib/artifacts/surface-schema.generated.ts
 * - src/lib/artifacts/surface.ts
 * - src/lib/grammar/labels.ts
 * - src/lib/grammar/types.ts
 * - src/lib/grammar/version.ts
 * - src/lib/surface-edge/build.ts
 * - src/lib/surface-edge/compile.ts
 * - src/lib/surface-edge/emit.ts
 * - src/lib/surface-edge/hints.ts
 * - src/lib/surface-edge/refs.ts
 * - src/lib/surface-edge/resolve.ts
 * - src/lib/surface-edge/spec.ts
 */
export const COMPILER_BUILD_SHA256 =
	"sha256:e2ddc267bf2f7799a06c821f4d43e9ebabca268b577f4c62c58457e98a30d8c8" as const;
